language: node_js

node_js:
  - '6'

addons:
  firefox: "39.0"

before_install:
  - "npm config set spin false"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: "npm run validate"

sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

after_script:
  - cat test/coverage/PhantomJS\ 2.1.1\ \(Linux\ 0.0.0\)/lcov.info | coveralls --verbose
